name: Create Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Optionally trigger for tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Adjust the Java version as needed
        distribution: 'adopt'

    - name: Build project
      run: mvn clean package  # This builds the Maven project

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: "Release ${{ github.ref_name }}"
        draft: false
        prerelease: false
        body: |
          Automated release for version ${{ github.ref_name }}.

    - name: Upload build artifact (optional)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/your_project.jar  # Adjust the path to your built artifact
        asset_name: your_project.jar  # Adjust the name of the artifact
        asset_content_type: application/java-archive
